name: say
descripcion: to say something
inputs:
  msg:
    required: true
    type: string
    default: hello people
runs:
  using: "composite"
  steps:
    - run: echo "${{ inputs.msg }}".
      shell: bash
