name: CI
on:
  push:
jobs:
  upload:
    runs-on: ubuntu-latest

    steps:    
    - env: 
        S3_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT }}
        AWS_ACCESS_KEY_ID: ${{ secrets.S3_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET }}
      run: |
        aws s3 ls --endpoint=${{ secrets.S3_ENDPOINT }} 
      
    
