name: CI
on:
  push:
jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - run: |
          node -v
          npm -v
          pip install boto3
          cat >prueba.py <<EOF
          import sys
          
          print(sys.argv[0])
          print(sys.argv[1])

          EOF
          cat prueba.py
          python prueba.py hola
