name: say
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
        default: julius
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: string
        default: julius
jobs:
  say:
    runs-on: ubuntu-latest

    steps:
    - run: echo "${{ inputs.name }}"
