name: test2
on:
  workflow_dispatch:

jobs:
  say:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - run: pwd; ls -alh .github/actions
    - uses: ./.github/actions/say
      with:
        name: monatest
