name: test2
on:
  workflow_dispatch:

jobs:
  say:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - uses: ./.github/actions/say
      with:
        msg: monatest
